services:
  db:
    container_name: postgres-2
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:  123
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: